#### Transforms data based on user defined fun

In [1]:
# 9th notebook

import pandas as pd
import numpy as np
import math
from sklearn.preprocessing import FunctionTransformer

In [2]:
# dummy dataset
arr = np.array([[0, -1],
               [-6, 7]])

arr

array([[ 0, -1],
       [-6,  7]])

In [3]:
abs_transformer = FunctionTransformer(func = np.abs, 
                                      validate=False) # if true converts input to 2d mat b4 transformation
abs_transformer.transform(arr)

array([[0, 1],
       [6, 7]])

In [4]:
# fun to be used with FnTransformer
def calculate_squares(x):
    return x * x

In [5]:
squares_transformer = FunctionTransformer(calculate_squares, validate = False)
squares_arr = squares_transformer.transform(arr)

squares_arr

array([[ 0,  1],
       [36, 49]])